# Main build settings for Netlify
[build]
  # The folder to publish for your static site (where quiz.html is)
  publish = "."
  # The folder where your serverless function is located
  functions = "quiz-backend/"

# API rewrite rule
# This sends all requests from /api/... to your server.js function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# Main page rewrite rule (Single Page App rule)
# This serves quiz.html for any path that is not an API call
[[redirects]]
  from = "/*"
  to = "/quiz.html"
  status = 200